name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.nightly }}

    strategy:
      fail-fast: false
      matrix:
        toolchain: [ 'stable' ]
        nightly: [false]
        include:
          - toolchain: 'nightly'
            nightly: true

    steps:
    - uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: clippy, rustfmt

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: rust_${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run test - sqlite | sqlx | runtime-async-std | macros
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features sqlite,sqlx,runtime-async-std,macros --all-targets --verbose

    - name: Run test - sqlite | diesel | runtime-async-std | macros
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features sqlite,diesel,runtime-async-std,macros --all-targets --verbose

    - name: Run test - sqlite | diesel
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features sqlite,diesel --all-targets --verbose

    - name: Start containers for database tests
      run: docker compose -f "docker-compose.yml" up -d

    - name: Run test - mysql | diesel
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features mysql,diesel --all-targets --verbose

    - name: Run test - mysql | sqlx | runtime-async-std
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features mysql,sqlx,runtime-async-std --all-targets --verbose

    - name: Stop containers for database tests
      if: always()
      run: docker compose -f "docker-compose.yml" down --volumes

    - name: Run doc tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features sqlite,sqlx,runtime-async-std,macros --doc --verbose

    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --features sqlite,sqlx,runtime-async-std,macros
